require 'pony'  
require 'yaml'  


module CitySDK
  yamlFile = '/var/www/citysdk/shared/config/mail.yaml'
  @@mail_opts = YAML.load_file(yamlFile)
  @@footer="\n\n---\nThis mail is automatically generated by the CitySDK endpoint running at " + `hostname`.strip + '.' + "\n"

  def self.sysmail(subject, body)
    Pony.mail({
      :to => 'citysdk@waag.org',
      :from => 'endpoint@citysdk.waag.org',
      :via => :smtp,
      :subject => subject, 
      :body => body + @@footer,
      :via_options => @@mail_opts 
    })
  end

  def self.mailto(to,subject, body)
    Pony.mail({
      :to => to,
      :from => 'endpoint@citysdk.waag.org',
      :via => :smtp,
      :subject => subject, 
      :body => body + @@footer,
      :via_options => @@mail_opts 
    })
  end

end


