# Find all venues where events have taken place since a given date

PREFIX ah: <http://purl.org/artsholland/1.0/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dc: <http://purl.org/dc/terms/>
PREFIX geo: <http://www.w3.org/2003/01/geo/wgs84_pos#>
PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>
PREFIX time: <http://www.w3.org/2006/time#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

SELECT DISTINCT ?v ?cidn ?title ?lat ?lon ?locality ?postalcode ?streetaddress ?telephone ?homepage WHERE {
	?v a ah:Venue ;	
    ah:cidn ?cidn ;
		dc:title ?title ;
		geo:lat ?lat ;
		geo:long ?lon ;
		#ah:venueType ?venuetype ;
	
		ah:locationAddress ?a .
    
	OPTIONAL {
		?v ah:telephone ?telephone .
		?v foaf:homepage ?homepage.
	}  
	
	?e a ah:Event ;
		ah:venue ?v ;
		time:hasBeginning ?time .		
		
	?a vcard:locality ?locality ;
		vcard:postal-code ?postalcode ;
		vcard:street-address ?streetaddress .

	FILTER langMatches( lang(?title), "nl" ) .	
	
	FILTER(?time >= "%s"^^xsd:dateTime) .
} ORDER BY ?title