source "https://rubygems.org"

gem "sinatra", :require => "sinatra/base"
gem "sinatra-sequel"
gem 'citysdk'
gem 'pony'
gem "sequel"
gem "rgeo"
gem "rgeo-geojson"
gem "i18n"
gem "active_support"
gem "pg"
gem "logger"
gem "faraday"
gem "passenger"
gem "sinatra-session"
